import os, json, glob
from datetime import datetime

ROOT = os.path.abspath(os.path.dirname(__file__))

# Folders you showed exist inside paper/
EVAL_DIRS = [
    "eval_real_only",
    "eval_ablation_final",
]

JOURNAL_FIGS = "journal_figs"

def read_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def find_metrics_json():
    """Find all metrics.json under eval folders."""
    found = []
    for d in EVAL_DIRS:
        base = os.path.join(ROOT, d)
        if not os.path.isdir(base):
            continue
        for p in glob.glob(os.path.join(base, "**", "metrics.json"), recursive=True):
            found.append(p)
    return sorted(found)

def safe_get(d, keys, default=None):
    cur = d
    for k in keys:
        if isinstance(cur, dict) and k in cur:
            cur = cur[k]
        else:
            return default
    return cur

def format_float(x):
    try:
        return f"{float(x):.4f}"
    except Exception:
        return "NA"

def build_auto_results(tex_path="auto_results.tex"):
    metric_files = find_metrics_json()

    lines = []
    lines.append("% Auto-generated by make_paper_assets.py")
    lines.append(f"% Generated: {datetime.now().isoformat(timespec='seconds')}")
    lines.append("")
    if not metric_files:
        lines.append("\\textbf{Auto Results:} No metrics.json files were found.\\par")
        lines.append("Expected under: eval_real_only/ or eval_ablation_final/\\par")
        with open(os.path.join(ROOT, tex_path), "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return

    # Try to form an ablation table (method name from folder)
    rows = []
    for mf in metric_files:
        data = read_json(mf)
        # Method name = parent folder name (e.g., j2, selective, raw_diffusion, real_only)
        method = os.path.basename(os.path.dirname(mf))
        # Common key guesses:
        acc = safe_get(data, ["accuracy"], safe_get(data, ["acc"], safe_get(data, ["Accuracy"])))
        f1  = safe_get(data, ["macro_f1"], safe_get(data, ["f1_macro"], safe_get(data, ["Macro-F1"])))
        auc = safe_get(data, ["macro_auc"], safe_get(data, ["auc_macro"], safe_get(data, ["AUC"])))

        rows.append((method, format_float(acc), format_float(f1), format_float(auc)))

    lines.append("\\subsection{Quantitative Results}")
    lines.append("Table~\\ref{tab:auto_metrics} summarizes the metrics parsed from available \\texttt{metrics.json} outputs.")
    lines.append("")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\caption{Automatically collected results from experiment folders (parsed from \\texttt{metrics.json}).}")
    lines.append("\\label{tab:auto_metrics}")
    lines.append("\\begin{tabular}{lccc}")
    lines.append("\\toprule")
    lines.append("Method & Accuracy & Macro-F1 & Macro-AUC \\\\")
    lines.append("\\midrule")
    for method, acc, f1, auc in rows:
        method_tex = method.replace("_", "\\_")
        lines.append(f"{method_tex} & {acc} & {f1} & {auc} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    # Add confusion matrix if exists in eval_real_only
    cm_png = os.path.join(ROOT, "eval_real_only", "confusion_matrix.png")
    if os.path.isfile(cm_png):
        lines.append("\\subsection{Confusion Matrix}")
        lines.append("\\begin{figure}[H]")
        lines.append("\\centering")
        lines.append("\\includegraphics[width=0.78\\linewidth]{eval_real_only/confusion_matrix.png}")
        lines.append("\\caption{Confusion matrix for the real-only evaluation setting.}")
        lines.append("\\label{fig:auto_cm}")
        lines.append("\\end{figure}")
        lines.append("")

    with open(os.path.join(ROOT, tex_path), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def build_auto_figs(tex_path="auto_figs.tex"):
    """
    Auto-insert:
      - attention_selective/*.png
      - roc_selective/*.png
      - plus any other pngs inside journal_figs/*
    """
    base = os.path.join(ROOT, JOURNAL_FIGS)
    lines = []
    lines.append("% Auto-generated by make_paper_assets.py")
    lines.append(f"% Generated: {datetime.now().isoformat(timespec='seconds')}")
    lines.append("")

    if not os.path.isdir(base):
        lines.append("\\textbf{Auto Figures:} journal_figs/ folder not found.\\par")
        with open(os.path.join(ROOT, tex_path), "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return

    # Collect attention maps
    attn_dir = os.path.join(base, "attention_selective")
    roc_dir  = os.path.join(base, "roc_selective")

    def include_all_pngs(folder, title, label_prefix):
        if not os.path.isdir(folder):
            return
        pngs = sorted(glob.glob(os.path.join(folder, "*.png")))
        if not pngs:
            return
        lines.append(f"\\subsection{{{title}}}")
        # Insert in a grid-like way (2 per row)
        for i, p in enumerate(pngs):
            rel = os.path.relpath(p, ROOT).replace("\\", "/")
            lines.append("\\begin{figure}[H]")
            lines.append("\\centering")
            lines.append(f"\\includegraphics[width=0.62\\linewidth]{{{rel}}}")
            cap = os.path.basename(p).replace("_", "\\_")
            lines.append(f"\\caption{{{cap}}}")
            lines.append(f"\\label{{fig:{label_prefix}_{i}}}")
            lines.append("\\end{figure}")
            lines.append("")

    include_all_pngs(roc_dir, "ROC Curves (Auto)", "roc")
    include_all_pngs(attn_dir, "Attention Rollout (Auto)", "attn")

    # Also include any top-level pngs in journal_figs
    top_pngs = sorted(glob.glob(os.path.join(base, "*.png")))
    if top_pngs:
        lines.append("\\subsection{Additional Figures (Auto)}")
        for i, p in enumerate(top_pngs):
            rel = os.path.relpath(p, ROOT).replace("\\", "/")
            lines.append("\\begin{figure}[H]")
            lines.append("\\centering")
            lines.append(f"\\includegraphics[width=0.75\\linewidth]{{{rel}}}")
            cap = os.path.basename(p).replace("_", "\\_")
            lines.append(f"\\caption{{{cap}}}")
            lines.append(f"\\label{{fig:extra_{i}}}")
            lines.append("\\end{figure}")
            lines.append("")

    if len(lines) <= 3:
        lines.append("\\textbf{Auto Figures:} No PNG figures found inside journal_figs/.\\par")

    with open(os.path.join(ROOT, tex_path), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    build_auto_results("auto_results.tex")
    build_auto_figs("auto_figs.tex")
    print("Generated: auto_results.tex and auto_figs.tex inside paper/")
